### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nachoan** [pauln/moodle-assignsubmission_onlineaudio#11]
Hi,

When I try to send the recorded file  I have this error. What can I do?

Debug info: Object of class assign_submission_onlineaudio could not be converted to string
Error code: codingerror
Stack trace:

    line 393 of /lib/setuplib.php: coding_exception thrown
    line 210 of /mod/assign/submission/onlineaudio/locallib.php: call to default_error_handler()
    line 289 of /mod/assign/submission/onlineaudio/locallib.php: call to assign_submission_onlineaudio->print_user_files()
    line 248 of /mod/assign/assignmentplugin.php: call to assign_submission_onlineaudio->get_form_elements()
    line 5990 of /mod/assign/locallib.php: call to assign_plugin->get_form_elements_for_user()
    line 6071 of /mod/assign/locallib.php: call to assign->add_plugin_submission_elements()
    line 48 of /mod/assign/submission_form.php: call to assign->add_submission_form_elements()
    line 191 of /lib/formslib.php: call to mod_assign_submission_form->definition()
    line 3322 of /mod/assign/locallib.php: call to moodleform->moodleform()
    line 516 of /mod/assign/locallib.php: call to assign->view_edit_submission_page()
    line 53 of /mod/assign/view.php: call to assign->view()

Thanks in advance

-----------------------
Moodle 2.7.1
Onlineaudio 1.2.1

**Comment by pauln** [comment]
This should now be fixed in v1.2.2.
