### ISSUE TITLE
Audio file is associated with wrong submission is assignment is reopened

### ISSUE THREAD

**Issue by dredix84** [pauln/moodle-assignsubmission_onlineaudio#14]
**How to produce bug**
Student submits an audio file for an assignment then the teacher reopens the submission. When the student attempt to make a new submission, the new audio record is attached to the previous assignment submission an not the current.

The student will never be able to submit his work after the assignment has been reopened. As seen in the image below, the new audio uploads are associated with the previous upload attempt.
![2016-06-10 12_10_09-assignment](https://cloud.githubusercontent.com/assets/2334674/15974205/8457063a-2f04-11e6-98ed-61751a6bb83f.png)

**Comment by pauln** [comment]
Thanks for reporting this bug, and providing enough detail to confirm and reproduce it.  I'll try to investigate and fix it soon - though I'll gladly took at a pull request if you're able to work on it before I get to it.

**Comment by dredix84** [comment]
Hello Paul,
I will take a look today to see if I can fix the issue.

*André N. Dixon*

---
<http://www.dredix.net/>
Making technology work for you
*DreDix Inc* www.dredix.net

<http://www.wpspartans.com>
Your 24/7 WordPress support experts.
*WP Spartans* www.wpspartans.com

**Comment by pauln** [comment]
Hi @dredix84,
Sorry this took so long to get around to - but I've just released v1.2.3, which fixes this issue.

-Paul
