### ISSUE TITLE
https

### ISSUE THREAD

**Issue by nachoan** [pauln/moodle-assignsubmission_onlineaudio#9]
Hi, 

When online submission is under ssl 443 https://url I have this error:

The page at 'https://myschool/mod/assign/view.php?id=2972&action=editsubmission' was loaded over HTTPS, but displayed insecure content from 'http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif': this content should also be loaded over HTTPS.

Thanks

**Comment by pauln** [comment]
Oops - somehow the actual fix didn't make it into 1.2.1.  It'll be in 1.2.2, available shortly here and in the plugins database, along with a fix for another issue.
